name = "fastauth-worker"
compatibility_date = "2023-01-01"
node_compat = true
main = "src/index.js"
# compatibility_flags = [ "nodejs_compat"  ]

[observability]
enabled = true

[env.production]
[env.production.vars]
ENVIRONMENT='development'
NETWORK='testnet'
FIREWALL='FALSE'
FASTAUTH_CONTRACT_ID='1732136407269-fastauth.testnet'

[env.dev]
[env.dev.vars]
ENVIRONMENT='development'
NETWORK='testnet'
FIREWALL='FALSE'
FASTAUTH_CONTRACT_ID='1732574588415-fastauth.testnet'
ORACLE_ACCOUNT_ID='fastauth-oracle-1.testnet'
MPC_CONTRACT_ID='v1.signer-prod.testnet'
